# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'spanjaan.snowflake::lang.models.page.label'

# Model Form Field configuration
form: $/spanjaan/snowflake/models/element/fields.yaml

# Model Class name
modelClass: SpAnjaan\Snowflake\Models\Element

# Default redirect location
defaultRedirect: spanjaan/snowflake/pages

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/snowflake/pages/update/:id
    redirectClose: spanjaan/snowflake/pages

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/snowflake/pages
    redirectClose: spanjaan/snowflake/pages

# Preview page
preview:
    title: backend::lang.form.preview_title
